from pydantic import BaseModel, Field
from .planner_result import PlannerResult
from .planner_reviewer_output import PlannerReviewerOutput

class PlannerReviewerInput(BaseModel):
    plan: PlannerResult = Field(description="The plan generated by the planner agent.")
    report_history: PlannerReviewerOutput = Field(description=" The history/results from previous review iterations. ")