from pydantic import BaseModel, Field
from .prover_result import ProverResult
from .problem_summary import ProblemSummary

class ProverReviewerInput(BaseModel):
    proof: ProverResult = Field(description="The proof generated by the ProverAgent.")
    problem_summary: ProblemSummary= Field(description=" Summary of the problem extracted by the ProblemSpecification Agent. ")