from pydantic import BaseModel, Field
from .prover_result import ProverResult
from .prover_reviewer_output import ProverReviewerOutput

class ProverReviewerInput(BaseModel):
    proof: ProverResult = Field(description="The proof generated by the ProverAgent.")
    report_history: ProverReviewerOutput = Field(description=" The history/results from previous review iterations. ")