from typing import Literal

from agents import Agent, Runner, RunConfig
from pydantic import BaseModel

from ...schemas import (ExperimentConfig, ExperimentOverview, PlannerInput, PlannerResult, PlannerReviewerInput,
                        PlannerReviewerOutput, ProblemSummary, ProverInput, ProverReviewerInput,
                        ProverReviewerOutput)
from ._update_planner_reviewer_history import update_planner_reviewer_history
from ._update_prover_reviewer_history import update_prover_reviewer_history


async def agent_reviewer_loop(main_agent: Agent,
                              reviewer_agent: Agent,
                              problem_summary: ProblemSummary,
                              plan: PlannerResult | None,
                              experiment_config: ExperimentConfig,
                              experiment_overview: ExperimentOverview,
                              loop_name: Literal["planner", "prover"]) -> tuple[BaseModel, BaseModel]:

    """Run a main agent and a reviewer agent in a loop.

    Calls main_agent, then reviewer_agent on its result, and repeats until the
    reviewer approves the result or experiment_config.max_reviewer_iterations
    is reached. This captures the pattern shared by the
    PlannerAgent-PlannerReviewerAgent and ProverAgent-ProverReviewerAgent
    loops; loop_name selects which of the two.

    Args:
        main_agent: PlannerAgent or ProverAgent.
        reviewer_agent: PlannerReviewerAgent or ProverReviewerAgent, matching main_agent.
        problem_summary: Summary of the problem extracted by the ProblemSpecificationAgent.
        plan: The plan generated by the PlannerAgent. Required for loop_name "prover",
            unused for loop_name "planner".
        experiment_config: Configuration of the experiment; provides the model name and
            the maximum number of reviewer iterations.
        experiment_overview: Overview of the experiment; its iteration counter for
            loop_name is incremented after every iteration.
        loop_name: Whether this is the "planner" or "prover" loop.

    Returns:
        A tuple of the final result of main_agent and the final reviewer history.

    Raises:
        ValueError: If loop_name is neither "planner" nor "prover", or if
            reviewer_agent's output does not match the expected type.
    """

    history: PlannerReviewerOutput | ProverReviewerOutput
    if loop_name == "planner":
        history = PlannerReviewerOutput(error_description=[], plan_ok=False)
        main_prompt = "Plan a proof: "
        reviewer_prompt = "Review the plan given in "
    elif loop_name == "prover":
        history = ProverReviewerOutput(error_description=[], proof_ok=False)
        main_prompt = "Generate a complete proof: "
        reviewer_prompt = "Review the proof given in "
    else:
        raise ValueError(f"loop_name must be 'planner' or 'prover', got '{loop_name}'.")

    def iterations_done() -> int:
        return experiment_overview.planner_reviewer_iterations if loop_name == "planner" \
            else experiment_overview.prover_reviewer_iterations

    def is_ok() -> bool:
        return history.plan_ok if isinstance(history, PlannerReviewerOutput) else history.proof_ok

    main_result = None

    while not is_ok() and iterations_done() < experiment_config.max_reviewer_iterations:

        first_iteration = iterations_done() == 0

        if isinstance(history, PlannerReviewerOutput):
            main_input = PlannerInput(problem_summary=problem_summary,
                                      planner_reviewer_feedback=None if first_iteration else history)
        else:
            assert plan is not None
            main_input = ProverInput(plan=plan,
                                     problem_summary=problem_summary,
                                     prover_reviewer_feedback=None if first_iteration else history)

        main_run = await Runner.run(starting_agent=main_agent,
                                    input=f"{main_prompt}{main_input}",
                                    run_config=RunConfig(model=experiment_config.model_name))
        main_result = main_run.final_output

        if isinstance(history, PlannerReviewerOutput):
            reviewer_input = PlannerReviewerInput(plan=main_result, problem_summary=problem_summary)
        else:
            reviewer_input = ProverReviewerInput(proof=main_result, problem_summary=problem_summary)

        reviewer_run = await Runner.run(starting_agent=reviewer_agent,
                                        input=f"{reviewer_prompt}{reviewer_input}",
                                        run_config=RunConfig(model=experiment_config.model_name))
        reviewer_feedback = reviewer_run.final_output

        if isinstance(history, PlannerReviewerOutput):
            if not isinstance(reviewer_feedback, PlannerReviewerOutput):
                raise ValueError(f"{reviewer_agent.name} output is not of type PlannerReviewerOutput!")
            history = update_planner_reviewer_history(history, reviewer_feedback)
        else:
            if not isinstance(reviewer_feedback, ProverReviewerOutput):
                raise ValueError(f"{reviewer_agent.name} output is not of type ProverReviewerOutput!")
            history = update_prover_reviewer_history(history, reviewer_feedback)

        experiment_overview.update_reviewer_iterations(loop_name)

    assert main_result is not None
    return main_result, history
