from pydantic import BaseModel, Field
from .planner_result import PlannerResult
from .problem_summary import ProblemSummary

class PlannerReviewerInput(BaseModel):
    plan: PlannerResult = Field(description="The plan generated by the planner agent.")
    problem_summary: ProblemSummary= Field(description=" Summary of the problem extracted by the ProblemSpecification Agent. ")