from pydantic import BaseModel, Field
from .planner_result import PlannerResult
from .problem_summary import ProblemSummary
from .prover_reviewer_output import ProverReviewerOutput

class ProverInput(BaseModel):
    plan: PlannerResult = Field(description=" Plan generated by the PlannerAgent ")
    problem_summary: ProblemSummary = Field(description=" Summary of the problem extracted by the ProblemSpecificationAgent. ")
    prover_reviewer_feedback: ProverReviewerOutput | None = Field(default= None,
                                                                   description=
                                                                   ("""The review of the ProverReviewerAgent. The ProverReviewerOutput class
                                                                    is used to save the feedbacks of a ProverAgent-ProverReviewerAgent loop.
                                                                    If the ProverAgent is called the first time, this attribute is set to None."""))
